In [2]:
# mode: r(read), w(write), a(append)
f = open('agencies.txt', 'r')
# Read all the content to a list
lines= f.readlines()
for li in lines:
    print(li.strip())  #strip loai bo ki tu 
    
f.close()


Federal Bureau of Investigation
Central Intelligence Agency
The Triboro Bridge and Tunnel Authority
Housing and Urban Development
The Metropolitan Transit Authority
The Port Authority of New York and New Jersey


In [ ]:
# Read authors.txt print name & email

f = open('authors.txt','r')
#Skip 3 frist lines
for _ in range(3):
    next(f)
# TODO: split line to get name & email
for line in f:
    name, email = line.split('<')
    name= name.strip()+":"
    email = email.strip()[:-1]
    print(f'{name:25}{email:25}')
f.close()


In [1]:
import numpy as np
data = np.loadtxt('falling.txt', skiprows=5)
print(data)


[[  0.    0.  180.    3.5]
 [  1.    0.5 185.    4.5]
 [  2.    0.7 192.    5.2]]


In [2]:
times = data[:, 1]
print(times)
hegights = data[:, 2]
print(hegights)


[0.  0.5 0.7]
[180. 185. 192.]


In [4]:
times, hegights = np.loadtxt('falling.txt', skiprows=5, usecols=(1, 2), unpack=True)
print(times)
print(hegights)

[0.  0.5 0.7]
[180. 185. 192.]


In [ ]:
student_data= np.loadtxt('gradebook.csv',delimiter=',',skiprows=1,dtype=str)
print(student_data)

In [22]:
# clear student_data
for student in student_data:
    if student[4] == '':
        student[4] = '0'
    if float(student[4]) > 10:
        student[4] = '10'
    if student[2] == '':
        student[2] = 'GCH22000'

# Print student data
#for student in student_data:
#    if float(student[4]) >=6.5:
#        print(f'{student[2]:10}{student[3]:20}{student[4]:10}')

pass_students =[['Login', 'Email','Code','Name','Grade']]
pass_students += [student for student in student_data if float(student[4])>=6.5]
for st in pass_students:
    print(f'{student[2]:10}{student[3]:20}{student[4]:10}')

#Write to file
np.savetxt('pass_student.csv',pass_students,delimiter=',',fmt='%s')

GCH22000  Nguyen Minh Tuan    10        
GCH22000  Nguyen Minh Tuan    10        
GCH22000  Nguyen Minh Tuan    10        
GCH22000  Nguyen Minh Tuan    10        
GCH22000  Nguyen Minh Tuan    10        
GCH22000  Nguyen Minh Tuan    10        
GCH22000  Nguyen Minh Tuan    10        


In [25]:
codes, names, grades = np.loadtxt('gradebook.csv', delimiter=',', skiprows=1,
                                  usecols=(2, 3, 4), dtype=str, unpack=True)
for i in range(len(codes)):
    if grades[i] == '':
        grades[i] = '0'
    if codes[i] == '':
        codes[i] = 'GCH22000'
    if float(grades[i]) > 10:
        grades[i] = '10'
for i in range(len(codes)):
    if float(grades[i]) >= 6.5:
        print(f'{codes[i]:10}{names[i]:20}{grades[i]:10}')
header='Code,Name,Grade'
np.savetxt('clean_gradebook.csv',np.column_stack((codes,names,grades)),delimiter=',',fmt='%s',header='Code,Name,Grade')

print('Done')

GBH17538  Le Minh Huong       6.5       
GCH16336  Nguyen The Dat      6.5       
GCH16388  Pham Minh Thang     9.5       
GCH16573  Do Duy Tung         6.5       
GCH16603  Nguyen Thanh Thang  8.0       
GCH22000  Nguyen Minh Tuan    10        
Done


In [19]:
f = open('agencies.txt','r')
fw = open('agencies_authority.txt','w') # Mở một file để ghi
# read content line by line
for line in f:
    if 'authority' in line.lower():
        print(line.strip())
        fw.write(line) # thực hiện ghi
    
f.close()
fw.close() # Đóng File

The Triboro Bridge and Tunnel Authority
The Metropolitan Transit Authority
The Port Authority of New York and New Jersey


In [28]:
import csv
with open('gradebook.csv','r') as f:
    reader = csv.reader(f)
    fw=open('fail_student.csv','w')
    writer= csv.writer(fw)
    writer.writerow(next(reader))       #writer header
    for row in reader:
        if row[4] == '':
            row[4] = '0'
        if row[2] == '':
            row[2] = 'GCH22000'
        if float(row[4]) > 10:
            row[4] = '10'
        if float(row[4]) < 6.5:
            writer.writerow(row)
    fw.close()
print('Done')


Done


In [42]:
#encoding='utf-8' format chữ and kí tự
#Clean pizza_data.csv
#Remove rows that have empty menus.amountMax, menus.amountMin
#Remove rows that have empty priceRangeMax, priceRangeMin ->set to 0
with open('pizza_data.csv','r') as f:
    reader= csv.reader(f)
    header= next(reader)
    del header[0]
    del header[7]    
    fw=open('clean_pizza_data.csv','w')
    writer= csv.writer(fw)
    writer.writerow(header)
    for row in reader:
        if row[9] =='':
            continue
        if row[10] =='':
            continue
        if row[18] == '':
            row[18] = '0'
        if row[19] =='':
            row[19]='0'
        row[2] = row[2].split(',')[0]
        del row[0]
        del row[7]
        writer.writerow(row)
    fw.close()
print('Clean data pizza succefully')
#Remove id column, url column

Clean data pizza succefully
