In [21]:
products = ['pencil','eraser','ruler','pen','notebook']
prices = [1000, 500, 2000, 5000,10000]
sold = [120,1000,80,50,30]

#Find product that has the highest sold

max_sold = prices[0] * sold[0]
i_max = 0
n = len(products)
for i in range(1, n): #for(i=1; i<n;i++)
    if prices[i] * sold[i] > max_sold:
        max_sold = prices[i] * sold[i]  #update max_sold
        i_max = i                       #update position of max_sold
        
print(f'{products[i_max]} has the highest sold: {max_sold}')
i_min = 0
min_sold =  prices[0] * sold[0]
#Find product that has the lowest sold
for i in range(1, n): #for(i=1; i<n;i++)
    if prices[i] * sold[i] < min_sold:
        min_sold = prices[i] * sold[i]  #update max_sold
        i_min = i      

print(f'{products[i_min]} has the lowest sold: {min_sold}')


# Find product that has the highest price
max_price = prices[0]
p_max=0
for i in range(n): #for(i=0; i<n;i++)
    if prices[i] > max_price:
        max_price =prices[i]
        p_max = i
        
print(f'{products[p_max]} has highest price: {max_price}')



# Find product that has lowest price
min_price = prices[0]
p_min = 0
for i in range(n): #for(i=0; i<n;i++)
    if prices[i] < min_price:
        min_price = prices[i]
        p_min = i
        
print(f'{products[p_min]} has lowest price: {min_price}')

# Find product that has sold the most
max_sold = sold[0]
s_max = 0
for i in range(n): #for(i=0; i<n;i++)
    if sold[i] > max_sold:
        max_sold =sold[i]
        s_max = i
        
print(f'{products[s_max]} has Highest price: {max_sold}')

# Find product that has sold the least 

min_sold = sold[0]
s_min = 0
for i in range(n): #for(i=0; i<n;i++)
    if sold[i] < min_sold:
        min_sold =sold[i]
        s_min = i
        
print(f'{products[s_min]} has lowest price: {min_sold}')





eraser has the highest sold: 500000
pencil has the lowest sold: 120000
notebook has highest price: 10000
eraser has lowest price: 500
eraser has Highest price: 1000
notebook has lowest price: 30


In [8]:
products_sold = [['pencil', 1000, 120],
                 ['earse', 500, 1000],
                 ['ruler', 2000, 80],
                 ['pen', 5000, 50],
                 ['notebook', 10000, 30]]

In [23]:
#Find product that has the highest sold

n = len(products_sold)
i_max = i
max_sold = products_sold[0][1] * products_sold[0][2]
for i in range(n):
    if products_sold[i][1]* products_sold[i][2] > max_sold:
        max_sold = products_sold[i][1]* products_sold[i][2]
        i_max = i

print(f'{products_sold[i_max][0]} the highest sold:{max_sold}')

#Find product that has the lowest sold

n = len(products_sold)
i_max = 0
max_sold = products_sold[0][1] * products_sold[0][2]
for i in range(n):
    if products_sold[i][1]* products_sold[i][2] < max_sold:
        max_sold = products_sold[i][1]* products_sold[i][2]
        i_max = i

print(f'{products_sold[i_max][0]} the lowest sold:{max_sold}')


# Find product that has the highest price

max_price = products_sold[0][1]
p_m =0
for i in range(n):
    if max_price < products_sold[i][1]:
        max_price = products_sold[i][1]
        p_max = i
print(f'{products_sold[p_max][0]} the highest price:{max_price}')
    

#Find product that has the lowest price

min_price = products_sold[0][1]
p_min = 0
for i in range(n):
    if min_price > products_sold[i][1]:
        min_price = products_sold[i][1]
        p_min = i
print(f'{products_sold[p_min][0]} the lowest price:{min_price}')

# Find product that has sold the most

# Find product that has sold the least 


earse the highest sold:500000
pencil the lowest sold:120000
notebook the highest price:10000
earse the lowest price:500


In [25]:
import random as round
numbers = [[1,2,3,4,5],
           [6,7,8,9,10],
           [11,12,13,14,15],
           [16,17,18,19,20],
           [20,21,22,23,24,25]]


In [27]:
# Get 3 middle rows in as many ways as you can
# Method 1
middle = numbers[1:4]
print(middle)
middle = numbers[1:-1]
print(middle)
middle = numbers[-4:-1]
print(middle)
middle = numbers[-4:4]
print(middle)

[[6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]
[[6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]
[[6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]
[[6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]


In [45]:
#Get 2 row cuoi
#Method 1
print(numbers[3:])
print(numbers[-2:])
print(numbers[3:5])

[[16, 17, 18, 19, 20], [20, 21, 22, 23, 24, 25]]
[[16, 17, 18, 19, 20], [20, 21, 22, 23, 24, 25]]
[[16, 17, 18, 19, 20], [20, 21, 22, 23, 24, 25]]


In [51]:
n = int(input('Enter n: '))
print(f'Max of row {n}: {max(numbers[n])}')
print(f'Min of row {n}: {min(numbers[n])}')
print(f'Sum of row {n}: {sum(numbers[n])}')

Max of row 2: 15
Min of row 2: 11
Sum of row 2: 65


In [53]:
import numpy as np
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
print(numbers, type(numbers))

[ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'>


In [54]:
a = ['hello',1,2,3,True]
b = np.array(a)
print(a, type(a))
print(b, type(b))

['hello', 1, 2, 3, True] <class 'list'>
['hello' '1' '2' '3' 'True'] <class 'numpy.ndarray'>


In [58]:
a = list(range(1,11))
print(a, type(a))
b = np.arange(1,11)
print(b, type(b))

#Full syntanx arange: np.arange(start, stop, step)
print(np.arange(10))
print(np.arange(1,20,2))
print(np.arange(0,20,2))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10] <class 'list'>
[ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
[ 1  3  5  7  9 11 13 15 17 19]
[ 0  2  4  6  8 10 12 14 16 18]


In [66]:
# Function linspace: np.linspace( start, stop, num, endpoint) 
print(np.linspace(1, 10, 10, dtype=int))
print(np.linspace(0, 10,10, endpoint=False, dtype=int))
print(np.linspace(1, 19, 10, dtype=int))
print(np.linspace(1, 18, 10, dtype=int))


[ 1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4 5 6 7 8 9]
[ 1  3  5  7  9 11 13 15 17 19]
[ 1  2  4  6  8 10 12 14 16 18]


In [68]:
print(np.arange(0, 10, 0.5))
print(np.linspace(0, 10, 20, endpoint=False))

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


In [82]:
# Function logspace: np.logspace(start, stop, num, endpoint, base)
a = np.linspace(1, 10, 10, endpoint=True, dtype=int)
b = 2**a
print(a)
print(b)
c = np.logspace(1, 10, 10, endpoint=True, base=2, dtype=int)
print(c)


[ 1  2  3  4  5  6  7  8  9 10]
[   2    4    8   16   32   64  128  256  512 1024]
[   2    4    8   16   32   64  128  256  512 1024]


In [81]:
a = np.logspace(0, 5, 6, endpoint=True, base=3, dtype=int)
print(a)
b = np.logspace(1, 6, 6, endpoint=True, base=10, dtype=int)
print(b)


[  1   3   9  27  81 243]
[     10     100    1000   10000  100000 1000000]


In [84]:
zeros = np.zeros(10, dtype=int)
ones = np.ones(10,dtype=int)
print(zeros)
print(ones)
print(ones*2)

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[2 2 2 2 2 2 2 2 2 2]


In [86]:
# Array operators: +,-,*,/,//,%,**
a = np.array([1, 2, 3, 4, 5])
print(a+2)
print(a-22)
print(a*2)
print(a/2)
print(a//2)
print(a % 2)
print(a**2)


[3 4 5 6 7]
[-21 -20 -19 -18 -17]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[0 1 1 2 2]
[1 0 1 0 1]
[ 1  4  9 16 25]


In [88]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a // b)
print(a % b)
print(a ** b)



[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[0 0 0 0 0]
[1 2 3 4 5]
[      1     128    6561  262144 9765625]


In [91]:
# Generate 10 random number in range [0,99]
numbers = np.random.randint(0, 100, 10)
print(numbers)
b = numbers % 2
print(b)
c = b == 0
print(c)
evens = numbers[c] #boolean indexing
print(evens)

[ 9 39 44 65 85 26  0 98 92  8]
[1 1 0 1 1 0 0 0 0 0]
[False False  True False False  True  True  True  True  True]
[44 26  0 98 92  8]


In [93]:
print(evens)
odds = numbers [numbers %2 ==1]
print(odds)

[44 26  0 98 92  8]
[ 9 39 65 85]


In [96]:
numbers = np.random.randint(-99, 100, 20)
print(numbers[numbers >0])
print(numbers[numbers <0])

[ 8 55 46 29  7 18 13 18 86 80 67 57 43]
[-54 -69 -73 -20 -37 -26 -40]


In [97]:
numbers[numbers < 0] = 0
print(numbers)

[ 8  0  0 55 46 29  7  0 18 13 18  0  0  0 86 80 67  0 57 43]


In [107]:
names = np.array(['Barrack Obama', 'Donal Trump','','Zoe Biden', "Messi"])
ages = np.array([59, 74, 78, -10, 272])
print(names)
names[names == ''] = "John Doe"
print(names)
print(ages)
ages[ages < 0 ] = 0
ages[ages > 150] = 150
print(ages)





['Barrack Obama' 'Donal Trump' '' 'Zoe Biden' 'Messi']
['Barrack Obama' 'Donal Trump' 'John Doe' 'Zoe Biden' 'Messi']
[ 59  74  78 -10 272]
[ 59  74  78   0 150]


In [109]:
print(f'Min age = {min(ages)}')
print(f'Max age = {max(ages)}')
print(f'Longest name: {max(names, key=len)}')
print(f'Shortest name: {min(names, key=len)}')



Min age = 0
Max age = 150
Longest name: Barrack Obama
Shortest name: Messi
