In [7]:
# pip install numpy
import numpy as np

y = np.array([0., 1.3, 5., 10.9, 18.9, 28.7, 40.])
t = np.array([0., 0.49, 1., 1.5, 2.08, 2.55, 3.2])
v = np.zeros(7)

#Cách 1
for i in range(1,7):
    v[i] =  (y[i] - y[i-1])/(t[i] - t[i-1])
print(v)

# Cách 2
v[1:] = (y[1:] - y[:-1]) / (t[1:] - t[:-1])
print(v)

[ 0.          2.65306122  7.25490196 11.8        13.79310345 20.85106383
 17.38461538]
[ 0.          2.65306122  7.25490196 11.8        13.79310345 20.85106383
 17.38461538]


In [9]:
# Mảng 2 chiều(2D arrays)
a = np.array([1, 2, 3, 4, 5, 6])
print(a, a.shape)

b = np.reshape(a, (2, 3))  # Convert 1D array to 2D array 2*3
print(b, b.shape)


[1 2 3 4 5 6] (6,)
[[1 2 3]
 [4 5 6]] (2, 3)


In [12]:
a = np.zeros((2, 3), dtype=int)
print(a)

# Return 6 evenly spaced numbers over the interval [0, 1]
a = np.linspace(0, 1, 6)
b = np.reshape(a, (2, 3))
print(b)


[[0 0 0]
 [0 0 0]]
[[0.  0.2 0.4]
 [0.6 0.8 1. ]]


In [14]:
a = np.random.randint(10, 100, (4, 4))
print(a)


[[45 68 44 19]
 [16 14 93 46]
 [38 47 28 96]
 [77 54 87 46]]
93


In [16]:
print(a[1][2], a[1, 2])
print(a[1:3, :])
print(a[:2, 1:3])


93 93
[[16 14 93 46]
 [38 47 28 96]]
[[68 44]
 [14 93]]


In [17]:
a = np.random.randint(1, 1000, (6, 6))
print(a)

[[421 531 127 543 928 593]
 [227 202 104 931 728 730]
 [839 509  95 320 375 377]
 [366 900 799 688 213 923]
 [847 636 873 157 296 989]
 [868  20 244 304 537 716]]


In [30]:
print(a[:,:1])
print('----------------')
print(a[1:4,2:5])
print('----------')
print(a[:2,3:])
print('---------')
print(a[3:,3:])

[[421]
 [227]
 [839]
 [366]
 [847]
 [868]]
----------------
[[104 931 728]
 [ 95 320 375]
 [799 688 213]]
----------
[[543 928 593]
 [931 728 730]]
---------
[[688 213 923]
 [157 296 989]
 [304 537 716]]


In [35]:
a[0] = 0
print(a)
print('-------------------------------')
a[2:4,3:5] = 0
print(a)


[[  0   0   0   0   0   0]
 [227 202 104 931 728 730]
 [839 509  95   0   0 377]
 [366 900 799   0   0 923]
 [847 636 873 157 296 989]
 [868  20 244 304 537 716]]
-------------------------------
[[  0   0   0   0   0   0]
 [227 202 104 931 728 730]
 [839 509  95   0   0 377]
 [366 900 799   0   0 923]
 [847 636 873 157 296 989]
 [868  20 244 304 537 716]]


In [46]:
# Exercise
# Create an 8 × 8 array with ones on all the edges and zeros everywhere else
a = np.ones((8, 8))
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [48]:
# Create an 8 × 8 array of integers with a checkerboard pattern of ones and zeros.
a = np.zeros((8, 8), dtype=int)
a[::2, ::2] = 1
a[1::2, 1::2] = 1
print(a)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [51]:
# Create an 8 x 8 array of random integers (0, 99), make all the numbers not divisible by 3 negative.
a = np.random.randint(10, 99, (8, 8))
a[a % 3 != 0] *= -1
print(a)


[[ 51 -97 -34 -19 -20 -74  24 -74]
 [-23  24 -31 -10  78 -82 -62  78]
 [-82 -79 -83  54 -79  12  54 -65]
 [ 63 -17  57 -67 -52  96  27 -37]
 [ 15 -26  18  45  60 -55 -41  21]
 [-95  60  15  54 -85 -61 -82 -79]
 [ 69  57  87 -56 -83  96 -83  12]
 [ 45 -98 -32  54 -95 -44  93 -76]]


In [58]:
b = a[:4, :4]
print(b)
print('-------------')
print(a[4:, 4:])
print('---------------')


[[ 51 -97 -34 -19]
 [-23  24 -31 -10]
 [-82 -79 -83  54]
 [ 63 -17  57 -67]]
-------------
[[ 60 -55 -41  21]
 [-85 -61 -82 -79]
 [-83  96 -83  12]
 [-95 -44  93 -76]]
---------------


In [59]:
print(b.size, b.shape, np.mean(b), np.std(b))

16 (4, 4) -18.3125 53.088038612760975
